[E 2025-09-04 21:16:39,722 C:\Users\gosto\AppData\Local\Programs\Python\Python311\Lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '114.38.153.85', 'person_id': 'P124428665', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2025-09-04 21:17:16,221 C:\Users\gosto\AppData\Local\Programs\Python\Python311\Lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '114.38.153.85', 'person_id': 'P124428665', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2025-09-04 21:21:54,110 C:\Users\gosto\AppData\Local\Programs\Python\Python311\Lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '114.38.153.85', 'person_id': 'P124428665', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2025-09-04 21:22:02,677 C:\Users\gosto\AppData\Local\Programs\Python\Python311\Lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '114.38.153.85', 'person_id': 'P124428665', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2025-09-04 21:30:46,205 C:\Users\gosto\AppData\Local\Programs\Python\Python311\Lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '114.38.153.85', 'person_id': 'P124428665', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2025-09-04 21:34:25,125 C:\Users\gosto\AppData\Local\Programs\Python\Python311\Lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '114.38.153.85', 'person_id': 'P124428665', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2025-09-09 11:07:31,305 C:\Users\windows10\AppData\Local\Programs\Python\Python311\Lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '118.170.142.112', 'person_id': 'P124428665', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
[E 2025-09-09 11:37:31,089 C:\Users\windows10\AppData\Local\Programs\Python\Python311\Lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 451}, 'response': {'token': '', 'accounts': [], 'detail': 'Too Many Connections.', 'ip_address': '118.170.142.112', 'person_id': 'P124428665', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
